version: '3'

services:
  nextcloud_origin:
    image: "nextcloud:latest"
    volumes:
      - carabam:/var/www/html
    command: exit 1
  nextcloud_1:
    build: "./nextcloud/"
    env_file:
     - ./.env
    restart: always
    volumes:
      - carabam:/var/www/html
    command: bash -c "/app/docker-settings.sh && php-fpm"
    depends_on:
        - mariadb
  nextcloud_2:
    build: "./nextcloud/"
    env_file:
      - ./.env
    restart: always
    volumes:
      - carabam:/var/www/html
    command: bash -c "/app/docker-settings.sh && php-fpm"
    depends_on:
        - mariadb
    links:
        - mariadb      
  nextcloud_3:
    build: "./nextcloud/"
    env_file:
     - ./.env
    restart: always
    volumes:
      - carabam:/var/www/html
    command: bash -c "/app/docker-settings.sh && php-fpm"
    depends_on:
        - mariadb
    expose:
      - '389'
    links:
        - mariadb      
  nginx:
    image: nginx
    restart: always
    ports:
        - 31007:80
    depends_on:
        - nextcloud_1
        - nextcloud_2
        - nextcloud_3
    links:
        - mariadb      
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - carabam:/var/www/html
  mariadb:
    image: "mariadb:10.4.8-bionic"
    env_file:
        - ./.env
    command: "--transaction-isolation=READ-COMMITTED --log-bin --binlog-format=ROW"
    restart: always
    volumes:
        - db:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
    expose:
      - '3306'
  openldap:
    build: "./openldap/"
    expose:
      - '389'

volumes:
  carabam:
  db:
  openldap_data:
    driver: local
    
